"""Add AI analysis fields

Revision ID: 19b7537be708
Revises: 0003_patient_identity_maps
Create Date: 2026-05-20 15:41:09.816753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b7537be708'
down_revision: Union[str, None] = '0003_patient_identity_maps'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE medicalimagestatus ADD VALUE IF NOT EXISTS 'analyzed'")
    op.add_column('medical_images', sa.Column('ai_prediction', sa.String(length=50), nullable=True))
    op.add_column('medical_images', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('medical_images', sa.Column('ai_gradcam_path', sa.String(length=512), nullable=True))
    op.add_column('medical_images', sa.Column('is_ambiguous', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index('ix_medical_images_stored_filename', table_name='medical_images')
    op.create_unique_constraint(None, 'medical_images', ['stored_filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medical_images', type_='unique')
    op.create_index('ix_medical_images_stored_filename', 'medical_images', ['stored_filename'], unique=True)
    op.drop_column('medical_images', 'is_ambiguous')
    op.drop_column('medical_images', 'ai_gradcam_path')
    op.drop_column('medical_images', 'ai_confidence')
    op.drop_column('medical_images', 'ai_prediction')
    # ### end Alembic commands ###
