"""Add latency to medical_images

Revision ID: 1f725101fe59
Revises: 19b7537be708
Create Date: 2026-05-20 17:44:56.861185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f725101fe59'
down_revision: Union[str, None] = '19b7537be708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_images', sa.Column('ai_latency_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_images', 'ai_latency_ms')
    # ### end Alembic commands ###
